version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-46-137-188-105.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: d6id1g0hg1nnfi
            ssl: true
            user: epmtcuwutltllu
            password: f486c81b90a3734d783ead1774f1811e31332c488253ff8638e871eb015b3109
            migrations: true

# version: '3'
# services:
#   prisma:
#     image: prismagraphql/prisma:1.19
#     restart: always
#     ports:
#     - "4466:4466"
#     environment:
#       PRISMA_CONFIG: |
#         port: 4466
#         managementApiSecret: mysecret42
#         databases:
#           default:
#             connector: postgres
#             host: host.docker.internal
#             port: 5432
#             user: prisma
#             password: prisma
#             migrations: true
#   postgres-db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_USER: prisma
#       POSTGRES_PASSWORD: prisma
#     volumes:
#       - postgres:/var/lib/postgresql/data
# volumes:
#   postgres: ~